######### NORMAL OPERATION  ###########

@baseUrl = http://localhost:3000

### Login Request
GET {{baseUrl}}/auths/login?username=test21&password=oue

### Register Request
POST {{baseUrl}}/auths/register
Content-Type: application/json

{
    "username":"test21",
    "password": "oue",
    "passwordC":"oue"
}




