######### NORMAL OPERATION  ###########

### Read all users
GET http://localhost:3000/users

### Read all pizzas with File variable
@baseUrl = http://localhost:3000

GET {{baseUrl}}/users

###ajouter user
POST {{baseUrl}}/users/register
Content-Type: application/json

{
    "username":"test brian",
    "password": "ddddd",
    "passwordC":"ddddd"
}


