/* eslint-disable no-dupe-keys */
/* eslint-disable quote-props */
const path = require('node:path');
const { parse } = require('../utils/json');

const jsonDbPath = path.join(__dirname, '/../data/pizzas.json');

const monstersList = [
  {
    id: 1,
    image: 'fire_monster1.png',
    nom: 'FeuMonstre1',
    type: 'feu',
    faiblesses: ['eau', 'terre'],
    resistances: ['feu'],
    pointsDeVie: 80,
    attaques: ['Boule de feu', 'Crocs ardents', 'Volcanique', 'Explosion de flammes'],
  },
  {
    id: 2,
    image: 'fire_monster2.png',
    nom: 'FeuMonstre2',
    type: 'feu',
    faiblesses: ['eau', 'terre'],
    resistances: ['feu'],
    pointsDeVie: 90,
    attaques: ['Chaleur intense', 'Boule de feu', 'Brasier furieux', 'Lance de feu'],
  },
  {
    id: 3,
    image: 'fire_monster3.png',
    nom: 'FeuMonstre3',
    type: 'feu',
    faiblesses: ['eau', 'terre'],
    resistances: ['feu'],
    pointsDeVie: 85,
    attaques: ['Flammèche', 'Chaleur intense', 'Inferno', 'Explosion pyrotechnique'],
  },
  {
    id: 4,
    image: 'fire_monster4.png',
    nom: 'FeuMonstre4',
    type: 'feu',
    faiblesses: ['eau', 'terre'],
    resistances: ['feu'],
    pointsDeVie: 95,
    attaques: ['Boule de feu', 'Flammèche', 'Brûlure persistante', 'Explosion incandescente'],
  },
  {
    id: 5,
    image: 'fire_monster5.png',
    nom: 'FeuMonstre5',
    type: 'feu',
    faiblesses: ['eau', 'terre'],
    resistances: ['feu'],
    pointsDeVie: 100,
    attaques: ['Crocs ardents', 'Chaleur intense', 'Fournaise', 'Déflagration'],
  },
  {
    id: 6,
    image: 'water_monster6.png',
    nom: 'EauMonstre1',
    type: 'eau',
    faiblesses: ['electric', 'plante'],
    resistances: ['feu', 'eau'],
    pointsDeVie: 70,
    attaques: ["Vague d'eau", 'Tornade', 'Tourbillon d\'eau', "Lame d'eau"],
  },
  {
    id: 7,
    image: 'water_monster7.png',
    nom: 'EauMonstre2',
    type: 'eau',
    faiblesses: ['electric', 'plante'],
    resistances: ['feu', 'eau'],
    pointsDeVie: 80,
    attaques: ['Coup de nageoire', 'Hydrocanon', 'Geyser', 'Éclaboussures électrifiées'],
  },
  {
    id: 8,
    image: 'water_monster8.png',
    nom: 'EauMonstre3',
    type: 'eau',
    faiblesses: ['electric', 'plante'],
    resistances: ['feu', 'eau'],
    pointsDeVie: 75,
    attaques: ["Jet d'eau", 'Averse', 'Bulle protectrice', 'Lacération aquatique'],
  },
  {
    id: 9,
    image: 'water_monster9.png',
    nom: 'EauMonstre4',
    type: 'eau',
    faiblesses: ['electric', 'plante'],
    resistances: ['feu', 'eau'],
    pointsDeVie: 85,
    attaques: ['Cascade', 'Bulles éclatantes', 'Torrent furieux', 'Inondation totale'],
  },
  {
    id: 10,
    image: 'water_monster10.png',
    nom: 'EauMonstre5',
    type: 'eau',
    faiblesses: ['electric', 'plante'],
    resistances: ['feu', 'eau'],
    pointsDeVie: 90,
    attaques: ["Vague d'eau", 'Averse', 'Vortex électromagnétique', 'Raz-de-marée'],
  },

  {
    id: 11,
    image: 'plant_monster11.png',
    nom: 'PlanteMonstre1',
    type: 'plante',
    faiblesses: ['feu', 'vol'],
    resistances: ['plante', 'electric', 'terre'],
    pointsDeVie: 70,
    attaques: ['Fouet végétal', 'Étreinte épineuse', 'Éruption de fleurs', 'Tempête de pétales'],
  },
  {
    id: 12,
    image: 'plant_monster12.png',
    nom: 'PlanteMonstre2',
    type: 'plante',
    faiblesses: ['feu', 'vol'],
    resistances: ['plante', 'electric', 'terre'],
    pointsDeVie: 80,
    attaques: [
      'Liane tranchante',
      'Feuilles tranchantes',
      'Croissance rapide',
      'Fleur empoisonnée',
    ],
  },
  {
    id: 13,
    image: 'plant_monster13.png',
    nom: 'PlanteMonstre3',
    type: 'plante',
    faiblesses: ['feu', 'vol'],
    resistances: ['plante', 'electric', 'terre'],
    pointsDeVie: 75,
    attaques: ['Bourgeonnement', 'Tornade florale', 'Danse des feuilles', 'Racine électrique'],
  },
  {
    id: 14,
    image: 'plant_monster14.png',
    nom: 'PlanteMonstre4',
    type: 'plante',
    faiblesses: ['feu', 'vol'],
    resistances: ['plante', 'electric', 'terre'],
    pointsDeVie: 85,
    attaques: ['Bombe végétale', 'Racines envahissantes', 'Vortex végétal', 'Sève acide'],
  },
  {
    id: 15,
    image: 'plant_monster15.png',
    nom: 'PlanteMonstre5',
    type: 'plante',
    faiblesses: ['feu', 'vol'],
    resistances: ['plante', 'electric', 'terre'],
    pointsDeVie: 90,
    attaques: ['Fouet végétal', 'Étreinte épineuse', 'Branche foudroyante', 'Vortex végétal'],
  },

  {
    id: 16,
    image: 'electric_monster16.png',
    nom: 'ElectriqueMonstre1',
    type: 'electric',
    faiblesses: ['terre'],
    resistances: ['eau', 'electric'],
    pointsDeVie: 70,
    attaques: ['Éclair rapide', 'Cage électrique', 'Orage dévastateur', 'Foudre en chaîne'],
  },
  {
    id: 17,
    image: 'electric_monster17.png',
    nom: 'ElectriqueMonstre2',
    type: 'electric',
    faiblesses: ['terre'],
    resistances: ['eau', 'electric'],
    pointsDeVie: 80,
    attaques: ['Rayon paralysant', 'Décharge électrique', 'Choc magnétique', 'Charge électrisante'],
  },
  {
    id: 18,
    image: 'electric_monster18.png',
    nom: 'ElectriqueMonstre3',
    type: 'electric',
    faiblesses: ['terre'],
    resistances: ['eau', 'electric'],
    pointsDeVie: 75,
    attaques: [
      'Foudre aveuglante',
      'Tempête statique',
      'Éclair fulgurant',
      'Vague électromagnétique',
    ],
  },
  {
    id: 19,
    image: 'electric_monster19.png',
    nom: 'ElectriqueMonstre4',
    type: 'electric',
    faiblesses: ['terre'],
    resistances: ['eau', 'electric'],
    pointsDeVie: 85,
    attaques: ['Électrochoc', 'Attaque électrique', 'Coup de tonnerre', 'Frappe statique'],
  },
  {
    id: 20,
    image: 'electric_monster20.png',
    nom: 'ElectriqueMonstre5',
    type: 'electric',
    faiblesses: ['terre'],
    resistances: ['eau', 'electric'],
    pointsDeVie: 90,
    attaques: [
      'Foudre aveuglante',
      'Tempête statique',
      'Rafale électrique',
      'Explosion électrique',
    ],
  },
  {
    id: 21,
    image: 'flying_monster21.png',
    nom: 'VolMonstre1',
    type: 'vol',
    faiblesses: ['electric'],
    resistances: ['vol', 'plante'],
    pointsDeVie: 70,
    attaques: ['Vent cinglant', 'Plongeon rapide', 'Tempête de griffes', 'Hurlement supersonique'],
  },
  {
    id: 22,
    image: 'flying_monster22.png',
    nom: 'VolMonstre2',
    type: 'vol',
    faiblesses: ['electric'],
    resistances: ['vol', 'plante'],
    pointsDeVie: 80,
    attaques: ['Tornade', 'Attaque aérienne', 'Danse des courants', 'Spirale ascendante'],
  },
  {
    id: 23,
    image: 'flying_monster23.png',
    nom: 'VolMonstre3',
    type: 'vol',
    faiblesses: ['electric'],
    resistances: ['vol', 'plante'],
    pointsDeVie: 75,
    attaques: ['Éclat aérien', "Tourbillon d'ailes", 'Frappe aérodynamique', 'Rafale électrifiée'],
  },
  {
    id: 24,
    image: 'flying_monster24.png',
    nom: 'VolMonstre4',
    type: 'vol',
    faiblesses: ['electric'],
    resistances: ['vol', 'plante'],
    pointsDeVie: 85,
    attaques: ['Rafale de plumes', "Nuage d'illusion", 'Vortex de vent', 'Déferlante céleste'],
  },
  {
    id: 25,
    image: 'flying_monster25.png',
    nom: 'VolMonstre5',
    type: 'vol',
    faiblesses: ['electric'],
    resistances: ['vol', 'plante'],
    pointsDeVie: 90,
    attaques: ['Vent cinglant', 'Plongeon rapide', 'Éclair stratosphérique', 'Vortex de vent'],
  },
  {
    id: 26,
    image: 'earth_monster26.png',
    nom: 'TerreMonstre1',
    type: 'terre',
    faiblesses: ['eau', 'plante'],
    resistances: ['terre', 'feu', 'electric'],
    pointsDeVie: 70,
    attaques: [
      'Secousse tellurique',
      'Jet de roches',
      'Tourbillon de gravier',
      'Éclatement tellurique',
    ],
  },
  {
    id: 27,
    image: 'earth_monster27.png',
    nom: 'TerreMonstre2',
    type: 'terre',
    faiblesses: ['eau', 'plante'],
    resistances: ['terre', 'feu', 'electric'],
    pointsDeVie: 80,
    attaques: ['Fracas sismique', 'attaque de pierre', 'Fissure profonde', 'Pluie de météorites'],
  },
  {
    id: 28,
    image: 'earth_monster28.png',
    nom: 'TerreMonstre3',
    type: 'terre',
    faiblesses: ['eau', 'plante'],
    resistances: ['terre', 'feu', 'electric'],
    pointsDeVie: 75,
    attaques: ['Lance de stalactites', 'Écrasement massif', 'Sables mouvants', 'Pilonnage géant'],
  },
  {
    id: 29,
    image: 'earth_monster29.png',
    nom: 'TerreMonstre4',
    type: 'terre',
    faiblesses: ['eau', 'plante'],
    resistances: ['terre', 'feu', 'electric'],
    pointsDeVie: 85,
    attaques: ['Rempart minéral', 'Éruption rocheuse', 'Champ magnétique', 'Déflagration minérale'],
  },
  {
    id: 30,
    image: 'earth_monster30.png',
    nom: 'TerreMonstre5',
    type: 'terre',
    faiblesses: ['eau', 'plante'],
    resistances: ['terre', 'feu', 'electric'],
    pointsDeVie: 90,
    attaques: ['Secousse tellurique', 'Jet de roches', 'Magma en fusion', 'Muraille de pierre'],
  },
];
const attacksAndDamage = [
  { name: 'Brûlure persistante', damage: 20, type: 'feu' },
  { name: 'Tourbillon d\'eau', damage: 12, type: 'eau' },
  { name: 'Coup de nageoire', damage: 15, type: 'eau' }, // normal ?
  { name: 'Geyser', damage: 15, type: 'eau' },
  { name: 'Bourgeonnement', damage: 17, type: 'plante' },
  { name: 'Vague électromagnétique', damage: 20 },
  { name: 'Sève acide', damage: 20, type: 'plante' },
  { name: 'Bombe végétale', damage: 12, type: 'plante' },
  { name: 'Racine électrique', damage: 15, type: 'electric' },
  { name: 'attaque de pierre', damage: 20, type: 'terre' },
  { name: 'Rafale électrifiée', damage: 12, type: 'electric' },
  { name: 'Éclat aérien', damage: 15, type: 'vol' },
  { name: 'Attaque aérienne', damage: 15, type: 'vol' },
  { name: 'Frappe statique', damage: 17, type: 'electric' }, // normal ?
  { name: 'Attaque électrique', damage: 20, type: 'electric' },
  { name: 'Muraille de pierre', damage: 20, type: 'terre' },
  { name: 'Magma en fusion', damage: 12, type: 'feu' },
  { name: 'Flammèche', damage: 15, type: 'feu' },
  { name: 'Cage électrique', damage: 15, type: 'electric' },
  { name: 'Orage dévastateur', damage: 17, type: 'electric' },
  { name: 'Foudre en chaîne', damage: 20, type: 'electric' },
  { name: 'Fleur empoisonnée', damage: 12, type: 'plante' },
  { name: 'Croissance rapide', damage: 14, type: 'plante' },
  { name: 'Feuilles tranchantes', damage: 19, type: 'plante' },
  { name: 'Rayon paralysant', damage: 13, type: 'electric' },
  { name: 'Décharge électrique', damage: 11, type: 'electric' },
  { name: 'Choc magnétique', damage: 17, type: 'electric' },
  { name: "Nuage d'illusion", damage: 11, type: 'vol' },
  { name: 'Cascade', damage: 20, type: 'eau' },
  { name: 'Torrent furieux', damage: 16, type: 'eau' },
  { name: 'Inondation totale', damage: 14, type: 'eau' },
  { name: 'Fouet végétal', damage: 11, type: 'plante' },
  { name: 'Étreinte épineuse', damage: 15, type: 'plante' },
  { name: 'Éruption de fleurs', damage: 12, type: 'plante' },
  { name: 'Tempête de pétales', damage: 19, type: 'plante' },
  { name: 'Averse', damage: 11, type: 'eau' },
  { name: 'Boule de feu', damage: 15, type: 'feu' },
  { name: 'Branche foudroyante', damage: 12, type: 'plante' },
  { name: 'Brasier furieux', damage: 19, type: 'feu' },
  { name: 'Bulles éclatantes', damage: 16, type: 'eau' },
  { name: 'Bulle protectrice', damage: 18, type: 'eau' },
  { name: 'Chaleur intense', damage: 12, type: 'feu' },
  { name: 'Charge électrisante', damage: 16, type: 'electric' },
  { name: 'Vortex électromagnétique', damage: 18, type: 'electric' },
  { name: 'Raz-de-marée', damage: 17, type: 'eau' },
  { name: 'Crocs ardents', damage: 18, type: 'feu' },
  { name: 'Coup de tonnerre', damage: 16, type: 'electric' },
  { name: 'Danse des courants', damage: 18, type: 'eau' },
  { name: 'Danse des feuilles', damage: 19, type: 'plante' },
  { name: 'Rempart minéral', damage: 15, type: 'eau' },
  { name: 'Champ magnétique', damage: 16, type: 'electric' },
  { name: 'Déflagration minérale', damage: 20, type: 'eau' },
  { name: 'Déflagration', damage: 15, type: 'feu' },
  { name: 'Déferlante céleste', damage: 17, type: 'terre' },
  { name: 'Déferlante électrique', damage: 20, type: 'electric' },
  { name: 'Éclair fulgurant', damage: 20, type: 'electric' },
  { name: 'Éclair rapide', damage: 15, type: 'electric' },
  { name: 'Éclair stratosphérique', damage: 16, type: 'vol' },
  { name: 'Éclair électrique', damage: 14, type: 'electric' },
  { name: 'Éclaboussures électrifiées', damage: 20, type: 'eau' },
  { name: 'Éclatement tellurique', damage: 18, type: 'terre' },
  { name: 'Écrasement massif', damage: 14, type: 'terre' }, // normal?
  { name: 'Écrasement de pierre', damage: 14, type: 'terre' },
  { name: 'Éruption rocheuse', damage: 11, type: 'terre' },
  { name: 'Explosion de flammes', damage: 17, type: 'feu' },
  { name: 'Explosion électrique', damage: 18, type: 'electric' },
  { name: 'Explosion incandescente', damage: 18, type: 'feu' },
  { name: 'Explosion pyrotechnique', damage: 13, type: 'feu' },
  { name: 'Fissure profonde', damage: 11, type: 'terre' },
  { name: 'Flammeche', damage: 16, type: 'feu' },
  { name: 'Fournaise', damage: 14, type: 'feu' },
  { name: 'Foudre aveuglante', damage: 11, type: 'electric' },
  { name: 'Fracas sismique', damage: 13, type: 'terre' },
  { name: 'Frappe aérodynamique', damage: 14, type: 'vol' },
  { name: 'Hurlement supersonique', damage: 19, type: 'electric' }, // normal ?
  { name: 'Hydrocanon', damage: 17, type: 'eau' },
  { name: 'Inferno', damage: 20, type: 'feu' },
  { name: "Jet d'eau", damage: 12, type: 'eau' },
  { name: 'Jet de roches', damage: 12, type: 'terre' },
  { name: 'Lacération aquatique', damage: 14, type: 'eau' },
  { name: "Lame d'eau", damage: 19, type: 'eau' },
  { name: 'Lance de stalactites', damage: 13, type: 'eau' },
  { name: 'Lance de feu', damage: 13, type: 'feu' },
  { name: 'Liane tranchante', damage: 18, type: 'plante' },
  { name: 'Plongeon rapide', damage: 19, type: 'vol' },
  { name: 'Pilonnage géant', damage: 16, type: 'terre' },
  { name: 'Pluie de météorites', damage: 12, type: 'feu' },
  { name: 'Rafale électrique', damage: 11, type: 'electric' },
  { name: 'Rafale de feuille', damage: 15, type: 'plante' },
  { name: 'Rafale de plumes', damage: 15, type: 'vol' },
  { name: 'Racines envahissantes', damage: 20, type: 'plante' },
  { name: 'Secousse tellurique', damage: 17, type: 'terre' },
  { name: 'Sables mouvants', damage: 15, type: 'terre' },
  { name: 'Spirale ascendante', damage: 12, type: 'vol' },
  { name: 'Tempête de griffes', damage: 17, type: 'vol' }, // normal
  { name: 'Tempête statique', damage: 13, type: 'vol' },
  { name: 'Tornade florale', damage: 16, type: 'plante' },
  { name: 'Tornade', damage: 13, type: 'vol' },
  { name: 'Tourbillon de gravier', damage: 17, type: 'terre' },
  { name: "Tourbillon d'ailes", damage: 16, type: 'vol' },
  { name: 'Tourbillon électrique', damage: 14, type: 'electric' },
  { name: "Vague d'eau", damage: 13, type: 'eau' },
  { name: 'Vent cinglant', damage: 16, type: 'vol' },
  { name: 'Volcanique', damage: 16, type: 'feu' },
  { name: 'Vortex de vent', damage: 13, type: 'vol' },
  { name: 'Vortex végétal', damage: 14, type: 'plante' },
  { name: 'Électrochoc', damage: 13, type: 'electric' },
];

function getAllMonsters() {
  const monsters = parse(jsonDbPath, monstersList);
  return monsters;
}
function getAllAttacks() {
  const attacks = parse(jsonDbPath, attacksAndDamage);
  return attacks;
}

function getMonstersByType(type) {
  const monsters = parse(jsonDbPath, monstersList);
  const monstersWithType = monsters.filter((monster) => monster.type === type);
  return monstersWithType;
}

module.exports = {
  getAllMonsters,
  getMonstersByType,
  getAllAttacks,
};
